Deprecate 'api key' in favor of 'token'
pantheon-systems/pantheon-content-cloud-sdk pull request #182
Opened 2024-02-09 11:58 UTC by kevinstubbs

2024-02-16 15:47 UTC, Aumkar requested changes

2024-02-16 15:47 UTC, Aumkar commented on packages/cli/src/lib/config.ts
> +    publishApiEndpoint:
Its already present as `publishEndpoint` variable.

2024-02-16 15:47 UTC, Aumkar commented on packages/cli/src/lib/addonApiHelper.ts
> +  static async publishFile(documentId: string) {
We can reuse `publishDocument` method.

2024-02-16 15:47 UTC, Aumkar commented on packages/cli/src/cli/commands/import.ts
> +        console.log(
Let's remove it if added for debugging

2024-02-22 13:31 UTC, a11rew approved these changes

2024-02-22 17:12 UTC, merged